server:
  port: 8081

cloud:
  aws:
    credentials:
      instanceProfile: true
      access_key: #your accessKey
      secret_key: #your secretKey
    region:
      static: ap-northeast-2
    s3:
      bucket: #your bucket
    stack:
      auto: false
